### ISSUE TITLE
Is this compatible with Vue2?

### ISSUE THREAD

**Issue by dante01yoon** [dillonchanis/vue-error-boundary#13]
Greetings, I see it's for composition api, not available for Vue2.

Do you have examples of vue2 for vue-error-boundary?

**Comment by dillonchanis** [comment]
Hey, sorry for the late reply. I believe the last version that was built on Vue 2 was [1.0.3](https://www.npmjs.com/package/vue-error-boundary/v/1.0.3). But if you'd rather just build a small component yourself it's really just a wrapper around the [errorCaptured API](https://v2.vuejs.org/v2/api/#errorCaptured)
