### ISSUE TITLE
2.0.2 is empty.  No `dist` folder or `js` files in node_modules/vue-error-boundary/

### ISSUE THREAD

**Issue by danielpclark** [dillonchanis/vue-error-boundary#15]
This was not something I would have guessed at so it took me a long time to track down.  But the npm package for 2.0.2 is empty of all except for the LICENSE, README, and package.json.  There are no project files in that version.

**Comment by dillonchanis** [comment]
Totally sorry about that! Should be fixed in 2.0.3!
