### ISSUE TITLE
Version 1.0.2 not working

### ISSUE THREAD

**Issue by wannesdebacker** [dillonchanis/vue-error-boundary#6]
vue-error-boundary 1.0.2 has no dist folder, probably has not been built before npm publish. v1.0.1 is working fine.

Same with the .umd build.

**Comment by dillonchanis** [comment]
Woops, my mistake you're right! Just pushed up another build where I actually built the thing...

Thanks for reaching out to me

V 1.0.3
[NPM](https://www.npmjs.com/package/vue-error-boundary)
[Unpkg Link](https://unpkg.com/vue-error-boundary@1.0.3/dist/vue-error-boundary.min.js)
